version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=test-user
      - POSTGRES_USER=test-user
      - POSTGRES_DB=note_service
    ports:
      - '5432:5432'
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local
# psql postgresql://test-user:test-user@localhost:5432/note_service
